1.Write a Python Program to Add Two Matrices?

In [10]:
import numpy as np
a=np.mat([[1,2,3],[4,5,6]])
print(a)
b=np.mat([[4,5,6],[1,2,3]])
print(b)
print("sum of matrices is")
print(a+b)

[[1 2 3]
 [4 5 6]]
[[4 5 6]
 [1 2 3]]
sum of matrices is
[[5 7 9]
 [5 7 9]]


2.Write a Python Program to Multiply Two Matrices?

In [15]:
import numpy as np
a=np.mat([[1,2],[5,6]])
print(a)
b=np.mat([[4,5],[1,2]])
print(b)
print("sum of matrices is")
print(a@b)
print(a*b)

[[1 2]
 [5 6]]
[[4 5]
 [1 2]]
sum of matrices is
[[ 6  9]
 [26 37]]
[[ 6  9]
 [26 37]]


3.Write a Python Program to Transpose a Matrix?

In [19]:
import numpy as np
a=np.mat([[1,2,3],[4,5,6]])
print(a)
b=a.T
print('after transpose')
print(b)

[[1 2 3]
 [4 5 6]]
after transpose
[[1 4]
 [2 5]
 [3 6]]


4.Write a Python Program to Sort Words in Alphabetic Order?

In [1]:
def sortString():
    in_string = input("Enter a String: ").title()
    sorted_list = sorted(in_string.split(' '))
    print(' '.join(sorted_list))
sortString()

Enter a String: surya teja all the best
All Best Surya Teja The


5.Write a Python Program to Remove Punctuation From a String?

In [2]:
def removePunctuatuions():
    punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''
    in_string = input('Enter a String: ')
    out_string = ''
    for ele in in_string:
        if ele not in punctuations:
            out_string += ele
    print(out_string)
    
removePunctuatuions()

Enter a String: su#rya$$%6t@#eja
surya6teja
